### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [7]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [22]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[479, 18, 140, 377], [479, 18, 140, 453], [479, 48, 140, 322], [423, 314, 123, 403, 468], [423, 314, 123, 403, 404], [122, 479, 358, 140, 45], [156, 373, 129, 403]]


### Word Embedding Represntation

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
import numpy as np

In [25]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 479  18 140 377]
 [  0   0   0   0 479  18 140 453]
 [  0   0   0   0 479  48 140 322]
 [  0   0   0 423 314 123 403 468]
 [  0   0   0 423 314 123 403 404]
 [  0   0   0 122 479 358 140  45]
 [  0   0   0   0 156 373 129 403]]


In [26]:
## 10 feature dimesnions
dim=10


In [27]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [29]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 479,  18, 140, 377], dtype=int32)

In [30]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 151ms/step


array([[-0.01479166, -0.03852754,  0.00639666,  0.04886765,  0.03230766,
         0.03064463,  0.03547312, -0.04019747, -0.03133973,  0.01553518],
       [-0.01479166, -0.03852754,  0.00639666,  0.04886765,  0.03230766,
         0.03064463,  0.03547312, -0.04019747, -0.03133973,  0.01553518],
       [-0.01479166, -0.03852754,  0.00639666,  0.04886765,  0.03230766,
         0.03064463,  0.03547312, -0.04019747, -0.03133973,  0.01553518],
       [-0.01479166, -0.03852754,  0.00639666,  0.04886765,  0.03230766,
         0.03064463,  0.03547312, -0.04019747, -0.03133973,  0.01553518],
       [ 0.02180118, -0.01516045,  0.0419925 , -0.00792675, -0.00124763,
         0.03842692,  0.00380111, -0.00837605, -0.03982817,  0.01398102],
       [ 0.04465587,  0.00408458,  0.00814425, -0.01278086, -0.02551764,
        -0.02760093, -0.02922372, -0.01007824, -0.00901613,  0.03240231],
       [-0.04175235, -0.03204318,  0.02812224, -0.00872163, -0.01558147,
         0.04766146, -0.00378424,  0.00557707

In [31]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 37ms/step
[[[-1.47916563e-02 -3.85275371e-02  6.39666244e-03  4.88676541e-02
    3.23076583e-02  3.06446292e-02  3.54731195e-02 -4.01974693e-02
   -3.13397273e-02  1.55351795e-02]
  [-1.47916563e-02 -3.85275371e-02  6.39666244e-03  4.88676541e-02
    3.23076583e-02  3.06446292e-02  3.54731195e-02 -4.01974693e-02
   -3.13397273e-02  1.55351795e-02]
  [-1.47916563e-02 -3.85275371e-02  6.39666244e-03  4.88676541e-02
    3.23076583e-02  3.06446292e-02  3.54731195e-02 -4.01974693e-02
   -3.13397273e-02  1.55351795e-02]
  [-1.47916563e-02 -3.85275371e-02  6.39666244e-03  4.88676541e-02
    3.23076583e-02  3.06446292e-02  3.54731195e-02 -4.01974693e-02
   -3.13397273e-02  1.55351795e-02]
  [ 2.18011774e-02 -1.51604526e-02  4.19924967e-02 -7.92675093e-03
   -1.24763325e-03  3.84269245e-02  3.80110741e-03 -8.37605074e-03
   -3.98281701e-02  1.39810182e-02]
  [ 4.46558706e-02  4.08457592e-03  8.14424828e-03 -1.27808563e-02
   -2.55176425e-02 -2.76009329e

In [32]:
embedded_docs[0]

array([  0,   0,   0,   0, 479,  18, 140, 377], dtype=int32)

In [33]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 18ms/step
[[-0.01479166 -0.03852754  0.00639666  0.04886765  0.03230766  0.03064463
   0.03547312 -0.04019747 -0.03133973  0.01553518]
 [-0.01479166 -0.03852754  0.00639666  0.04886765  0.03230766  0.03064463
   0.03547312 -0.04019747 -0.03133973  0.01553518]
 [-0.01479166 -0.03852754  0.00639666  0.04886765  0.03230766  0.03064463
   0.03547312 -0.04019747 -0.03133973  0.01553518]
 [-0.01479166 -0.03852754  0.00639666  0.04886765  0.03230766  0.03064463
   0.03547312 -0.04019747 -0.03133973  0.01553518]
 [ 0.02180118 -0.01516045  0.0419925  -0.00792675 -0.00124763  0.03842692
   0.00380111 -0.00837605 -0.03982817  0.01398102]
 [ 0.04465587  0.00408458  0.00814425 -0.01278086 -0.02551764 -0.02760093
  -0.02922372 -0.01007824 -0.00901613  0.03240231]
 [-0.04175235 -0.03204318  0.02812224 -0.00872163 -0.01558147  0.04766146
  -0.00378424  0.00557707 -0.02710739  0.02692131]
 [ 0.02558755 -0.00647474  0.04675886 -0.03804847  0.00907345 -0.04062295

In [35]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [36]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[479, 103, 291, 123, 461, 345], [430, 42, 291, 54, 254, 265], [423, 142, 281, 91], [479, 348, 291, 78, 479, 375], [216, 421, 38, 291, 54, 254, 265], [270, 291, 54, 254, 289, 209]]


In [37]:
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 479 103 291 123 461 345]
 [  0   0   0   0 430  42 291  54 254 265]
 [  0   0   0   0   0   0 423 142 281  91]
 [  0   0   0   0 479 348 291  78 479 375]
 [  0   0   0 216 421  38 291  54 254 265]
 [  0   0   0   0 270 291  54 254 289 209]]


In [38]:
model=Sequential()
model.add(Embedding(voc_size,20,input_length=sent_length))
model.compile('adam','mse')

In [39]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 20)            10000     
                                                                 
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [40]:
embedded_docs[0]

array([  0,   0,   0,   0, 479, 103, 291, 123, 461, 345], dtype=int32)

In [41]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 52ms/step


array([[-3.94291393e-02,  4.43190373e-02, -3.76258269e-02,
         1.98989250e-02, -4.10096869e-02,  3.82300466e-03,
        -2.12310627e-03,  5.09250909e-04,  4.35666777e-02,
         4.30043787e-03,  1.69475116e-02, -3.02501675e-02,
         1.40157081e-02,  2.22314335e-02, -1.01973861e-03,
        -4.73726913e-03,  3.19199674e-02, -2.70757433e-02,
         3.02135982e-02, -3.61883752e-02],
       [-3.94291393e-02,  4.43190373e-02, -3.76258269e-02,
         1.98989250e-02, -4.10096869e-02,  3.82300466e-03,
        -2.12310627e-03,  5.09250909e-04,  4.35666777e-02,
         4.30043787e-03,  1.69475116e-02, -3.02501675e-02,
         1.40157081e-02,  2.22314335e-02, -1.01973861e-03,
        -4.73726913e-03,  3.19199674e-02, -2.70757433e-02,
         3.02135982e-02, -3.61883752e-02],
       [-3.94291393e-02,  4.43190373e-02, -3.76258269e-02,
         1.98989250e-02, -4.10096869e-02,  3.82300466e-03,
        -2.12310627e-03,  5.09250909e-04,  4.35666777e-02,
         4.30043787e-03,  1.6

In [42]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 34ms/step
[[[-0.03942914  0.04431904 -0.03762583 ... -0.02707574  0.0302136
   -0.03618838]
  [-0.03942914  0.04431904 -0.03762583 ... -0.02707574  0.0302136
   -0.03618838]
  [-0.03942914  0.04431904 -0.03762583 ... -0.02707574  0.0302136
   -0.03618838]
  ...
  [-0.02804887 -0.02996588  0.03580343 ... -0.04380972  0.02437773
   -0.02391111]
  [-0.01807541  0.02700791 -0.00279889 ... -0.04356042 -0.02107601
    0.02802832]
  [-0.03312676 -0.02343793  0.03962251 ... -0.00855511  0.0143781
   -0.01899922]]

 [[-0.03942914  0.04431904 -0.03762583 ... -0.02707574  0.0302136
   -0.03618838]
  [-0.03942914  0.04431904 -0.03762583 ... -0.02707574  0.0302136
   -0.03618838]
  [-0.03942914  0.04431904 -0.03762583 ... -0.02707574  0.0302136
   -0.03618838]
  ...
  [-0.04140381  0.03556067  0.03188405 ... -0.04906628  0.04312548
    0.04373569]
  [ 0.02012159 -0.03423196  0.00892054 ...  0.0248847  -0.01784603
   -0.0010994 ]
  [ 0.02367761 -0.01506938  

In [43]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[-3.94291393e-02  4.43190373e-02 -3.76258269e-02  1.98989250e-02
  -4.10096869e-02  3.82300466e-03 -2.12310627e-03  5.09250909e-04
   4.35666777e-02  4.30043787e-03  1.69475116e-02 -3.02501675e-02
   1.40157081e-02  2.22314335e-02 -1.01973861e-03 -4.73726913e-03
   3.19199674e-02 -2.70757433e-02  3.02135982e-02 -3.61883752e-02]
 [-3.94291393e-02  4.43190373e-02 -3.76258269e-02  1.98989250e-02
  -4.10096869e-02  3.82300466e-03 -2.12310627e-03  5.09250909e-04
   4.35666777e-02  4.30043787e-03  1.69475116e-02 -3.02501675e-02
   1.40157081e-02  2.22314335e-02 -1.01973861e-03 -4.73726913e-03
   3.19199674e-02 -2.70757433e-02  3.02135982e-02 -3.61883752e-02]
 [-3.94291393e-02  4.43190373e-02 -3.76258269e-02  1.98989250e-02
  -4.10096869e-02  3.82300466e-03 -2.12310627e-03  5.09250909e-04
   4.35666777e-02  4.30043787e-03  1.69475116e-02 -3.02501675e-02
   1.40157081e-02  2.22314335e-02 -1.01973861e-03 -4.73726913e-03
   3.19199674e-02 -2.7